version: '3.8'

services:
  orchestrator:
    build:
      context: .
      dockerfile: orchestrator/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DEV_MODE=true
      - DEBUG=true
      - MCP_SERVERS={"salesforce_mcp": "http://salesforce_mcp:8001"}
    env_file:
      - orchestrator/.env
    depends_on:
      - salesforce_mcp
    networks:
      - mcp_network

  salesforce_mcp:
    build:
      context: .
      dockerfile: mcps/salesforce_mcp/Dockerfile
    ports:
      - "8001:8001"
    environment:
      - DEV_MODE=true
      - DEBUG=true
    env_file:
      - mcps/salesforce_mcp/.env
    networks:
      - mcp_network

networks:
  mcp_network:
    driver: bridge
